name: kadima
favicon: null
layout_spectrum: 0.55349
typography_spectrum: 0.49075
title: Kadima
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#100806'
    - '#4c4f49'
    - '#c4b867'
    - '#ff7154'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.47611387888900936
  rhythmicContrast: 0.75
purpose: []
