analytics: {}
color:
  brandColors:
    - '#AED0F3'
    - '#A79200'
    - '#3B5000'
    - '#637D00'
    - '#F8F083'
  brandStrength: 0.341216
  lightness: 0.381756
  rhythmicContrast: 0.576576
  saturation: 0.358108
cta: {}
layout_spectrum: 0.55543
name: Kadima
opengraph: {}
purpose: []
typography_spectrum: 0.534909
