analytics: {}
color:
  brandColors:
    - '#AED0F3'
    - '#A79200'
    - '#3B5000'
    - '#637D00'
    - '#F8F083'
  brandStrength: 0.507882
  lightness: 0.504504
  rhythmicContrast: 0.511261
  saturation: 0.497747
cta: {}
layout_spectrum: 0.55543
name: Kadima
opengraph: {}
purpose: []
typography_spectrum: 0.534909
