name: kadima
favicon: null
layout_spectrum: 0.21916
typography_spectrum: 0.23204
title: Kadima
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1d741'
    - '#66b5e3'
    - '#1d77b9'
    - '#f72928'
    - '#1d0000'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
