analytics: {}
color:
  brandColors:
    - '#AED0F3'
    - '#A79200'
    - '#3B5000'
    - '#637D00'
    - '#F8F083'
  brandStrength: 0.384009
  lightness: 0.625
  rhythmicContrast: 0.51126
  saturation: 0.726351
cta: {}
layout_spectrum: 0.73536
name: Kadima
opengraph: {}
purpose: []
typography_spectrum: 0.757882
