name: Kadima
favicon: null
layout_spectrum: 0.21916
typography_spectrum: 0.1428
title: Kadima
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0b07'
    - '#b5e5ef'
    - '#8b6d6b'
    - '#ffa861'
    - '#e74543'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
