name: Kadima
favicon: null
layout_spectrum: 0.06457
typography_spectrum: 0.534909
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#AED0F3'
    - '#A79200'
    - '#3B5000'
    - '#637D00'
    - '#F8F083'
  brandStrength: 0.384009
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.51126
purpose: []
