analytics: {}
color:
  brandColors:
    - '#AED0F3'
    - '#A79200'
    - '#3B5000'
    - '#637D00'
    - '#F8F083'
  brandStrength: 0.503378
  lightness: 0.788288
  rhythmicContrast: 0.63063
  saturation: 0.760135
cta: {}
layout_spectrum: 0.911036
name: Kadima
opengraph: {}
purpose: []
typography_spectrum: 0.757882
