name: Kadima
favicon: null
layout_spectrum: 0.49089
typography_spectrum: 0.792792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#AED0F3'
    - '#A79200'
    - '#3B5000'
    - '#637D00'
    - '#F8F083'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.760135
  rhythmicContrast: 0.519144
purpose: []
