name: Kadima
favicon: null
layout_spectrum: 0.55543
typography_spectrum: 0.5086
title: Kadima
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aed0f3'
    - '#a79200'
    - '#3b5000'
    - '#637d00'
    - '#f8f083'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
