analytics: {}
color:
  brandColors:
    - '#AED0F3'
    - '#A79200'
    - '#3B5000'
    - '#637D00'
    - '#F8F083'
  brandStrength: 0
  lightness: 0.382882
  rhythmicContrast: 0.487612
  saturation: 0.1509
cta: {}
layout_spectrum: 0.55543
name: Kadima
opengraph: {}
purpose: []
typography_spectrum: 0.534909
