analytics: {}
color:
  brandColors:
    - '#AED0F3'
    - '#A79200'
    - '#3B5000'
    - '#637D00'
    - '#F8F083'
  brandStrength: 0.239864
  lightness: 0.572072
  rhythmicContrast: 0.510135
  saturation: 0.23536
cta: {}
layout_spectrum: 0.55543
name: Kadima
opengraph: {}
purpose: []
typography_spectrum: 0.655405
